import 'package:test/test.dart';

import 'package:test_timeout_repro/everything.1.dart' as everything1;
import 'package:test_timeout_repro/everything.2.dart' as everything2;
import 'package:test_timeout_repro/everything.3.dart' as everything3;
import 'package:test_timeout_repro/everything.4.dart' as everything4;
import 'package:test_timeout_repro/everything.5.dart' as everything5;
import 'package:test_timeout_repro/everything.6.dart' as everything6;
import 'package:test_timeout_repro/everything.7.dart' as everything7;
import 'package:test_timeout_repro/everything.8.dart' as everything8;
import 'package:test_timeout_repro/everything.9.dart' as everything9;
import 'package:test_timeout_repro/everything.10.dart' as everything10;
import 'package:test_timeout_repro/everything.11.dart' as everything11;
import 'package:test_timeout_repro/everything.12.dart' as everything12;
import 'package:test_timeout_repro/everything.13.dart' as everything13;
import 'package:test_timeout_repro/everything.14.dart' as everything14;
import 'package:test_timeout_repro/everything.15.dart' as everything15;
import 'package:test_timeout_repro/everything.16.dart' as everything16;
import 'package:test_timeout_repro/everything.17.dart' as everything17;
import 'package:test_timeout_repro/everything.18.dart' as everything18;
import 'package:test_timeout_repro/everything.19.dart' as everything19;
import 'package:test_timeout_repro/everything.20.dart' as everything20;
import 'package:test_timeout_repro/everything.21.dart' as everything21;
import 'package:test_timeout_repro/everything.22.dart' as everything22;
import 'package:test_timeout_repro/everything.23.dart' as everything23;
import 'package:test_timeout_repro/everything.24.dart' as everything24;
import 'package:test_timeout_repro/everything.25.dart' as everything25;
import 'package:test_timeout_repro/everything.26.dart' as everything26;
import 'package:test_timeout_repro/everything.27.dart' as everything27;
import 'package:test_timeout_repro/everything.28.dart' as everything28;
import 'package:test_timeout_repro/everything.29.dart' as everything29;
import 'package:test_timeout_repro/everything.30.dart' as everything30;
import 'package:test_timeout_repro/everything.31.dart' as everything31;
import 'package:test_timeout_repro/everything.32.dart' as everything32;
import 'package:test_timeout_repro/everything.33.dart' as everything33;
import 'package:test_timeout_repro/everything.34.dart' as everything34;
import 'package:test_timeout_repro/everything.35.dart' as everything35;
import 'package:test_timeout_repro/everything.36.dart' as everything36;
import 'package:test_timeout_repro/everything.37.dart' as everything37;
import 'package:test_timeout_repro/everything.38.dart' as everything38;
import 'package:test_timeout_repro/everything.39.dart' as everything39;
import 'package:test_timeout_repro/everything.40.dart' as everything40;
import 'package:test_timeout_repro/everything.41.dart' as everything41;
import 'package:test_timeout_repro/everything.42.dart' as everything42;
import 'package:test_timeout_repro/everything.43.dart' as everything43;
import 'package:test_timeout_repro/everything.44.dart' as everything44;
import 'package:test_timeout_repro/everything.45.dart' as everything45;
import 'package:test_timeout_repro/everything.46.dart' as everything46;
import 'package:test_timeout_repro/everything.47.dart' as everything47;
import 'package:test_timeout_repro/everything.48.dart' as everything48;
import 'package:test_timeout_repro/everything.49.dart' as everything49;
import 'package:test_timeout_repro/everything.50.dart' as everything50;
import 'package:test_timeout_repro/everything.51.dart' as everything51;
import 'package:test_timeout_repro/everything.52.dart' as everything52;
import 'package:test_timeout_repro/everything.53.dart' as everything53;
import 'package:test_timeout_repro/everything.54.dart' as everything54;
import 'package:test_timeout_repro/everything.55.dart' as everything55;
import 'package:test_timeout_repro/everything.56.dart' as everything56;
import 'package:test_timeout_repro/everything.57.dart' as everything57;
import 'package:test_timeout_repro/everything.58.dart' as everything58;
import 'package:test_timeout_repro/everything.59.dart' as everything59;
import 'package:test_timeout_repro/everything.60.dart' as everything60;
import 'package:test_timeout_repro/everything.61.dart' as everything61;
import 'package:test_timeout_repro/everything.62.dart' as everything62;
import 'package:test_timeout_repro/everything.63.dart' as everything63;
import 'package:test_timeout_repro/everything.64.dart' as everything64;
import 'package:test_timeout_repro/everything.65.dart' as everything65;
import 'package:test_timeout_repro/everything.66.dart' as everything66;
import 'package:test_timeout_repro/everything.67.dart' as everything67;
import 'package:test_timeout_repro/everything.68.dart' as everything68;
import 'package:test_timeout_repro/everything.69.dart' as everything69;
import 'package:test_timeout_repro/everything.70.dart' as everything70;
import 'package:test_timeout_repro/everything.71.dart' as everything71;
import 'package:test_timeout_repro/everything.72.dart' as everything72;
import 'package:test_timeout_repro/everything.73.dart' as everything73;
import 'package:test_timeout_repro/everything.74.dart' as everything74;
import 'package:test_timeout_repro/everything.75.dart' as everything75;
import 'package:test_timeout_repro/everything.76.dart' as everything76;
import 'package:test_timeout_repro/everything.77.dart' as everything77;
import 'package:test_timeout_repro/everything.78.dart' as everything78;
import 'package:test_timeout_repro/everything.79.dart' as everything79;
import 'package:test_timeout_repro/everything.80.dart' as everything80;
import 'package:test_timeout_repro/everything.81.dart' as everything81;
import 'package:test_timeout_repro/everything.82.dart' as everything82;
import 'package:test_timeout_repro/everything.83.dart' as everything83;
import 'package:test_timeout_repro/everything.84.dart' as everything84;
import 'package:test_timeout_repro/everything.85.dart' as everything85;
import 'package:test_timeout_repro/everything.86.dart' as everything86;
import 'package:test_timeout_repro/everything.87.dart' as everything87;
import 'package:test_timeout_repro/everything.88.dart' as everything88;
import 'package:test_timeout_repro/everything.89.dart' as everything89;
import 'package:test_timeout_repro/everything.90.dart' as everything90;
import 'package:test_timeout_repro/everything.91.dart' as everything91;
import 'package:test_timeout_repro/everything.92.dart' as everything92;
import 'package:test_timeout_repro/everything.93.dart' as everything93;
import 'package:test_timeout_repro/everything.94.dart' as everything94;
import 'package:test_timeout_repro/everything.95.dart' as everything95;
import 'package:test_timeout_repro/everything.96.dart' as everything96;
import 'package:test_timeout_repro/everything.97.dart' as everything97;
import 'package:test_timeout_repro/everything.98.dart' as everything98;
import 'package:test_timeout_repro/everything.99.dart' as everything99;
import 'package:test_timeout_repro/everything.100.dart' as everything100;
import 'package:test_timeout_repro/everything.101.dart' as everything101;
import 'package:test_timeout_repro/everything.102.dart' as everything102;
import 'package:test_timeout_repro/everything.103.dart' as everything103;
import 'package:test_timeout_repro/everything.104.dart' as everything104;
import 'package:test_timeout_repro/everything.105.dart' as everything105;
import 'package:test_timeout_repro/everything.106.dart' as everything106;
import 'package:test_timeout_repro/everything.107.dart' as everything107;
import 'package:test_timeout_repro/everything.108.dart' as everything108;
import 'package:test_timeout_repro/everything.109.dart' as everything109;
import 'package:test_timeout_repro/everything.110.dart' as everything110;
import 'package:test_timeout_repro/everything.111.dart' as everything111;
import 'package:test_timeout_repro/everything.112.dart' as everything112;
import 'package:test_timeout_repro/everything.113.dart' as everything113;
import 'package:test_timeout_repro/everything.114.dart' as everything114;
import 'package:test_timeout_repro/everything.115.dart' as everything115;
import 'package:test_timeout_repro/everything.116.dart' as everything116;
import 'package:test_timeout_repro/everything.117.dart' as everything117;
import 'package:test_timeout_repro/everything.118.dart' as everything118;
import 'package:test_timeout_repro/everything.119.dart' as everything119;
import 'package:test_timeout_repro/everything.120.dart' as everything120;
import 'package:test_timeout_repro/everything.121.dart' as everything121;
import 'package:test_timeout_repro/everything.122.dart' as everything122;
import 'package:test_timeout_repro/everything.123.dart' as everything123;
import 'package:test_timeout_repro/everything.124.dart' as everything124;
import 'package:test_timeout_repro/everything.125.dart' as everything125;

void main() {
  test('A test requiring many imports and thus many file downloads', () {
    expect(everything1.Everything().isAwesome, isTrue);
    expect(everything2.Everything().isAwesome, isTrue);
    expect(everything3.Everything().isAwesome, isTrue);
    expect(everything4.Everything().isAwesome, isTrue);
    expect(everything5.Everything().isAwesome, isTrue);
    expect(everything6.Everything().isAwesome, isTrue);
    expect(everything7.Everything().isAwesome, isTrue);
    expect(everything8.Everything().isAwesome, isTrue);
    expect(everything9.Everything().isAwesome, isTrue);
    expect(everything10.Everything().isAwesome, isTrue);
    expect(everything11.Everything().isAwesome, isTrue);
    expect(everything12.Everything().isAwesome, isTrue);
    expect(everything13.Everything().isAwesome, isTrue);
    expect(everything14.Everything().isAwesome, isTrue);
    expect(everything15.Everything().isAwesome, isTrue);
    expect(everything16.Everything().isAwesome, isTrue);
    expect(everything17.Everything().isAwesome, isTrue);
    expect(everything18.Everything().isAwesome, isTrue);
    expect(everything19.Everything().isAwesome, isTrue);
    expect(everything20.Everything().isAwesome, isTrue);
    expect(everything21.Everything().isAwesome, isTrue);
    expect(everything22.Everything().isAwesome, isTrue);
    expect(everything23.Everything().isAwesome, isTrue);
    expect(everything24.Everything().isAwesome, isTrue);
    expect(everything25.Everything().isAwesome, isTrue);
    expect(everything26.Everything().isAwesome, isTrue);
    expect(everything27.Everything().isAwesome, isTrue);
    expect(everything28.Everything().isAwesome, isTrue);
    expect(everything29.Everything().isAwesome, isTrue);
    expect(everything30.Everything().isAwesome, isTrue);
    expect(everything31.Everything().isAwesome, isTrue);
    expect(everything32.Everything().isAwesome, isTrue);
    expect(everything33.Everything().isAwesome, isTrue);
    expect(everything34.Everything().isAwesome, isTrue);
    expect(everything35.Everything().isAwesome, isTrue);
    expect(everything36.Everything().isAwesome, isTrue);
    expect(everything37.Everything().isAwesome, isTrue);
    expect(everything38.Everything().isAwesome, isTrue);
    expect(everything39.Everything().isAwesome, isTrue);
    expect(everything40.Everything().isAwesome, isTrue);
    expect(everything41.Everything().isAwesome, isTrue);
    expect(everything42.Everything().isAwesome, isTrue);
    expect(everything43.Everything().isAwesome, isTrue);
    expect(everything44.Everything().isAwesome, isTrue);
    expect(everything45.Everything().isAwesome, isTrue);
    expect(everything46.Everything().isAwesome, isTrue);
    expect(everything47.Everything().isAwesome, isTrue);
    expect(everything48.Everything().isAwesome, isTrue);
    expect(everything49.Everything().isAwesome, isTrue);
    expect(everything50.Everything().isAwesome, isTrue);
    expect(everything51.Everything().isAwesome, isTrue);
    expect(everything52.Everything().isAwesome, isTrue);
    expect(everything53.Everything().isAwesome, isTrue);
    expect(everything54.Everything().isAwesome, isTrue);
    expect(everything55.Everything().isAwesome, isTrue);
    expect(everything56.Everything().isAwesome, isTrue);
    expect(everything57.Everything().isAwesome, isTrue);
    expect(everything58.Everything().isAwesome, isTrue);
    expect(everything59.Everything().isAwesome, isTrue);
    expect(everything60.Everything().isAwesome, isTrue);
    expect(everything61.Everything().isAwesome, isTrue);
    expect(everything62.Everything().isAwesome, isTrue);
    expect(everything63.Everything().isAwesome, isTrue);
    expect(everything64.Everything().isAwesome, isTrue);
    expect(everything65.Everything().isAwesome, isTrue);
    expect(everything66.Everything().isAwesome, isTrue);
    expect(everything67.Everything().isAwesome, isTrue);
    expect(everything68.Everything().isAwesome, isTrue);
    expect(everything69.Everything().isAwesome, isTrue);
    expect(everything70.Everything().isAwesome, isTrue);
    expect(everything71.Everything().isAwesome, isTrue);
    expect(everything72.Everything().isAwesome, isTrue);
    expect(everything73.Everything().isAwesome, isTrue);
    expect(everything74.Everything().isAwesome, isTrue);
    expect(everything75.Everything().isAwesome, isTrue);
    expect(everything76.Everything().isAwesome, isTrue);
    expect(everything77.Everything().isAwesome, isTrue);
    expect(everything78.Everything().isAwesome, isTrue);
    expect(everything79.Everything().isAwesome, isTrue);
    expect(everything80.Everything().isAwesome, isTrue);
    expect(everything81.Everything().isAwesome, isTrue);
    expect(everything82.Everything().isAwesome, isTrue);
    expect(everything83.Everything().isAwesome, isTrue);
    expect(everything84.Everything().isAwesome, isTrue);
    expect(everything85.Everything().isAwesome, isTrue);
    expect(everything86.Everything().isAwesome, isTrue);
    expect(everything87.Everything().isAwesome, isTrue);
    expect(everything88.Everything().isAwesome, isTrue);
    expect(everything89.Everything().isAwesome, isTrue);
    expect(everything90.Everything().isAwesome, isTrue);
    expect(everything91.Everything().isAwesome, isTrue);
    expect(everything92.Everything().isAwesome, isTrue);
    expect(everything93.Everything().isAwesome, isTrue);
    expect(everything94.Everything().isAwesome, isTrue);
    expect(everything95.Everything().isAwesome, isTrue);
    expect(everything96.Everything().isAwesome, isTrue);
    expect(everything97.Everything().isAwesome, isTrue);
    expect(everything98.Everything().isAwesome, isTrue);
    expect(everything99.Everything().isAwesome, isTrue);
    expect(everything100.Everything().isAwesome, isTrue);
    expect(everything101.Everything().isAwesome, isTrue);
    expect(everything102.Everything().isAwesome, isTrue);
    expect(everything103.Everything().isAwesome, isTrue);
    expect(everything104.Everything().isAwesome, isTrue);
    expect(everything105.Everything().isAwesome, isTrue);
    expect(everything106.Everything().isAwesome, isTrue);
    expect(everything107.Everything().isAwesome, isTrue);
    expect(everything108.Everything().isAwesome, isTrue);
    expect(everything109.Everything().isAwesome, isTrue);
    expect(everything110.Everything().isAwesome, isTrue);
    expect(everything111.Everything().isAwesome, isTrue);
    expect(everything112.Everything().isAwesome, isTrue);
    expect(everything113.Everything().isAwesome, isTrue);
    expect(everything114.Everything().isAwesome, isTrue);
    expect(everything115.Everything().isAwesome, isTrue);
    expect(everything116.Everything().isAwesome, isTrue);
    expect(everything117.Everything().isAwesome, isTrue);
    expect(everything118.Everything().isAwesome, isTrue);
    expect(everything119.Everything().isAwesome, isTrue);
    expect(everything120.Everything().isAwesome, isTrue);
    expect(everything121.Everything().isAwesome, isTrue);
    expect(everything122.Everything().isAwesome, isTrue);
    expect(everything123.Everything().isAwesome, isTrue);
    expect(everything124.Everything().isAwesome, isTrue);
    expect(everything125.Everything().isAwesome, isTrue);
  });
}
